# Generated by Django 4.2.2 on 2023-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(verbose_name="Prénom")),
                ("last_name", models.CharField(verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("adress", models.CharField(null=True, verbose_name="Adresse")),
                (
                    "zip_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Code Postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=255, null=True, verbose_name="Ville"),
                ),
            ],
        ),
    ]
