# Generated by Django 4.2.2 on 2023-07-01 21:04

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="email",
            field=encrypted_fields.fields.EncryptedEmailField(
                max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="first_name",
            field=encrypted_fields.fields.EncryptedCharField(verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="patients",
            name="last_name",
            field=encrypted_fields.fields.EncryptedCharField(verbose_name="Nom"),
        ),
    ]
